services:
  # Anvil node
  anvil:
    image: inconetwork/local-node-anvil-${PEPPER}:${DOCKER_IMAGE_TAG}
    ports:
      - "8545:8545"

  # Covalidator service that waits for deployer to be healthy
  covalidator:
    image: inconetwork/local-node-covalidator-${PEPPER}:${DOCKER_IMAGE_TAG}
    depends_on:
      anvil:
        condition: service_healthy
    ports:
      - "50055:50055"
