import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import FaucetButton from '../components/FaucetButton';
import AddTwoValue from '../components/AddTwoValue';
import SendANumberToAddTwo from '../components/SendANumberToAddTwo';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <h1>Coucou</h1>
        <ConnectButton />
        <br/>
        <FaucetButton />
        <br/>
        "lastResult" as read from AddTwo contract: <AddTwoValue />
        <br/><br/>
        <SendANumberToAddTwo />
      </main>
    </div>
  );
};

export default Home;
